apiVersion: v1
kind: Pod
metadata:
  name: pod-udagram-reverseproxy
spec:
  containers:
  - image: hafizazman/udagram-reverseproxy
    name: reverseproxy
    imagePullPolicy: Always
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
  restartPolicy: Always